version: 2

jobs:
  # test:
  #   docker:
  #     - image: circleci/node:10
  #   steps:
  #     - checkout
  #     - run:
  #         name: Install project
  #         command: npm install
      #- run:
      #    name: Test project
      #    command: npm test

  docs-build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install project
          command: npm install
      - run:
          name: Build project
          command: npm run build-storybook
      - run:
          name: Checking directory paths
          command: ls -lrt -d -1 $PWD/{*,.*}
      - persist_to_workspace:
          root: ~/repo
          paths: storybook-static

  docs-deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Install and configure dependencies
          command: npm install -g gh-pages@2.0.1
      - add_ssh_keys:
          fingerprints:
            - "47:ea:88:91:2e:76:b5:8e:26:06:76:3d:d6:f7:9f:f7"
      - run:
          name: Deploy files to gh-pages branch
          command: gh-pages --message "ci Updates" --dist ~repo/storybook-static

workflows:
  version: 2
  build:
    jobs:
      - docs-build
      - docs-deploy:
          requires:
            - docs-build

#for when it's ready
# workflows:
#   version: 2
#   build:
#     jobs:
#       - docs-build
#       - docs-deploy:
#           requires:
#             - test
#             - docs-build
#           filters:
#             branches:
# only: master
